-- Script SQL para crear la tabla 'barra' para gestionar el banner promocional
-- Esta tabla almacena 3 líneas de texto que se mostrarán en el banner promocional

CREATE TABLE IF NOT EXISTS public.barra (
  id bigint generated by default as identity not null,
  line1 text null,
  line2 text null,
  line3 text null,
  constraint barra_pkey primary key (id)
) TABLESPACE pg_default;

-- Comentarios en las columnas para documentación
COMMENT ON TABLE public.barra IS 'Tabla para gestionar las líneas de texto del banner promocional que aparece en todas las páginas';
COMMENT ON COLUMN public.barra.line1 IS 'Primera línea de texto del banner promocional';
COMMENT ON COLUMN public.barra.line2 IS 'Segunda línea de texto del banner promocional';
COMMENT ON COLUMN public.barra.line3 IS 'Tercera línea de texto del banner promocional';

-- Insertar un registro inicial vacío (opcional)
-- INSERT INTO public.barra (line1, line2, line3) VALUES (NULL, NULL, NULL) ON CONFLICT DO NOTHING;
